apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "incorrect-set-2"
spec:
  configuration:
    clusters:
      - name: "standard"
        layout:
          shardsCount: 1
          replicasCount: 1
