# Template Parameters:
#
# OPERATOR_VERSION=0.23.0
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clickhousekeeperinstallations.clickhouse-keeper.altinity.com
  labels:
    clickhouse-keeper.altinity.com/chop: 0.23.0
spec:
  group: clickhouse-keeper.altinity.com
  scope: Namespaced
  names:
    kind: ClickHouseKeeperInstallation
    singular: clickhousekeeperinstallation
    plural: clickhousekeeperinstallations
    shortNames:
      - chk
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: status
          type: string
          description: CHK status
          jsonPath: .status.status
        - name: replicas
          type: integer
          description: Replica count
          priority: 1 # show in wide view
          jsonPath: .status.replicas
        - name: age
          type: date
          description: Age of the resource
          # Displayed in all priorities
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          description: "define a set of Kubernetes resources (StatefulSet, PVC, Service, ConfigMap) which describe behavior one ClickHouse Keeper cluster"
          properties:
            apiVersion:
              type: string
              description: |
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            kind:
              type: string
              description: |
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            metadata:
              type: object
            status:
              type: object
              description: |
                Current ClickHouseKeeperInstallation status, contains many fields like overall status, desired replicas and ready replica list with their endpoints
              properties:
                status:
                  type: string
                  description: "Status"
                replicas:
                  type: integer
                  format: int32
                  description: Replicas is the number of number of desired replicas in the cluster
                readyReplicas:
                  type: array
                  description: ReadyReplicas is the array of endpoints of those ready replicas in the cluster
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                        description: dns name or ip address for Keeper node
                      port:
                        type: integer
                        minimum: 0
                        maximum: 65535
                        description: TCP port which used to connect to Keeper node
                      secure:
                        type: string
                        description: if a secure connection to Keeper is required
            spec:
              type: object
              description: KeeperSpec defines the desired state of a Keeper cluster
              properties:
                type:
                  type: string
                  description: This is used by chi reconciliation.
                  enum:
                    - "Container"
                    - "Embedded"
                replicas:
                  type: integer
                  format: int32
                  description: |
                    Replicas is the expected size of the keeper cluster.
                    The valid range of size is from 1 to 7.
                  minimum: 1
                  maximum: 7
                settings:
                  type: object
                  description: "allows configure multiple aspects and behavior for `clickhouse-keeper` instance"
                  x-kubernetes-preserve-unknown-fields: true
                podTemplate:
                  type: object
                  description: |
                    podTemplate will use during render `Pod` inside `StatefulSet.spec` and allows define rendered `Pod.spec`, pod scheduling distribution and pod zone
                  properties:
                    metadata:
                      type: object
                      description: |
                        allows passing standard object's metadata from template to Pod
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
                      x-kubernetes-preserve-unknown-fields: true
                    spec:
                      # TODO specify PodSpec
                      type: object
                      description: "allows defining whole Pod.spec inside StatefulSet.spec, look to https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates for details"
                      x-kubernetes-preserve-unknown-fields: true
                volumeClaimTemplates:
                  type: array
                  description: "allows defining template for rendering `PVC` kubernetes resource, which would use inside `Pod` for mounting clickhouse `data`, clickhouse `logs` or something else"
                  items:
                    type: object
                    properties:
                      metadata:
                        type: object
                        description: |
                          allows to pass standard object's metadata from template to PVC
                          More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
                        x-kubernetes-preserve-unknown-fields: true
                      spec:
                        type: object
                        description: |
                          allows define all aspects of `PVC` resource
                          More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
                        x-kubernetes-preserve-unknown-fields: true
