apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
spec:
  defaults:
    templates:
      podTemplate: clickhouse-keeper
      volumeClaimTemplate: data-volume
      clusterServiceTemplate: zookeeper
  configuration:
    clusters:
      - name: test
        layout:
          replicasCount: 1
    settings:
        keeper_server/tcp_port: "2181"
  templates:
    podTemplates:
      - name: clickhouse-keeper
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: Always
              image: "clickhouse/clickhouse-keeper:24.8"
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    serviceTemplates: # Service drop-in replacement in tests
      - name: zookeeper
        generateName: zookeeper
        spec:
          ports:
            - port: 2181
              name: client
            - port: 7000
              name: prometheus
          type: ClusterIP
          clusterIP: None