apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
spec:
  configuration:
    clusters:
      - name: chcluster
        layout:
          shardsCount: 2
          replicasCount: 1
