/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1"
	scheme "github.com/altinity/clickhouse-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClickHouseOperatorConfigurationsGetter has a method to return a ClickHouseOperatorConfigurationInterface.
// A group's client should implement this interface.
type ClickHouseOperatorConfigurationsGetter interface {
	ClickHouseOperatorConfigurations(namespace string) ClickHouseOperatorConfigurationInterface
}

// ClickHouseOperatorConfigurationInterface has methods to work with ClickHouseOperatorConfiguration resources.
type ClickHouseOperatorConfigurationInterface interface {
	Create(ctx context.Context, clickHouseOperatorConfiguration *v1.ClickHouseOperatorConfiguration, opts metav1.CreateOptions) (*v1.ClickHouseOperatorConfiguration, error)
	Update(ctx context.Context, clickHouseOperatorConfiguration *v1.ClickHouseOperatorConfiguration, opts metav1.UpdateOptions) (*v1.ClickHouseOperatorConfiguration, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClickHouseOperatorConfiguration, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClickHouseOperatorConfigurationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClickHouseOperatorConfiguration, err error)
	ClickHouseOperatorConfigurationExpansion
}

// clickHouseOperatorConfigurations implements ClickHouseOperatorConfigurationInterface
type clickHouseOperatorConfigurations struct {
	client rest.Interface
	ns     string
}

// newClickHouseOperatorConfigurations returns a ClickHouseOperatorConfigurations
func newClickHouseOperatorConfigurations(c *ClickhouseV1Client, namespace string) *clickHouseOperatorConfigurations {
	return &clickHouseOperatorConfigurations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clickHouseOperatorConfiguration, and returns the corresponding clickHouseOperatorConfiguration object, and an error if there is any.
func (c *clickHouseOperatorConfigurations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClickHouseOperatorConfiguration, err error) {
	result = &v1.ClickHouseOperatorConfiguration{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClickHouseOperatorConfigurations that match those selectors.
func (c *clickHouseOperatorConfigurations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClickHouseOperatorConfigurationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClickHouseOperatorConfigurationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clickHouseOperatorConfigurations.
func (c *clickHouseOperatorConfigurations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clickHouseOperatorConfiguration and creates it.  Returns the server's representation of the clickHouseOperatorConfiguration, and an error, if there is any.
func (c *clickHouseOperatorConfigurations) Create(ctx context.Context, clickHouseOperatorConfiguration *v1.ClickHouseOperatorConfiguration, opts metav1.CreateOptions) (result *v1.ClickHouseOperatorConfiguration, err error) {
	result = &v1.ClickHouseOperatorConfiguration{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clickHouseOperatorConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clickHouseOperatorConfiguration and updates it. Returns the server's representation of the clickHouseOperatorConfiguration, and an error, if there is any.
func (c *clickHouseOperatorConfigurations) Update(ctx context.Context, clickHouseOperatorConfiguration *v1.ClickHouseOperatorConfiguration, opts metav1.UpdateOptions) (result *v1.ClickHouseOperatorConfiguration, err error) {
	result = &v1.ClickHouseOperatorConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		Name(clickHouseOperatorConfiguration.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clickHouseOperatorConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clickHouseOperatorConfiguration and deletes it. Returns an error if one occurs.
func (c *clickHouseOperatorConfigurations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clickHouseOperatorConfigurations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clickHouseOperatorConfiguration.
func (c *clickHouseOperatorConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClickHouseOperatorConfiguration, err error) {
	result = &v1.ClickHouseOperatorConfiguration{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clickhouseoperatorconfigurations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
