// Code generated by client-gen. DO NOT EDIT.

package v1

type ClickHouseInstallationExpansion interface{}

type ClickHouseInstallationTemplateExpansion interface{}

type ClickHouseOperatorConfigurationExpansion interface{}
