// Copyright 2019 Altinity Ltd and/or its affiliates. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package util

import (
	dumper "github.com/sanity-io/litter"
)

// Dump dumps object into string with repeatable order
func Dump(obj interface{}) (out string) {
	defer func() {
		if r := recover(); r != nil {
			out = ""
		}
	}()

	d := dumper.Options{
		Separator: " ",
		StrictGo:  true,
		//Compact           :true,
		//StripPackageNames :true,
		//HidePrivateFields: true,
		//FieldExclusions:   regexp.MustCompile(`^(XXX_.*)$`), // XXX_ is a prefix of fields generated by protoc-gen-go
		//HideZeroValues    :true,
		//DisablePointerReplacement : true,
	}
	return d.Sdump(obj)
}
