apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "standard-02-deployment-pv"
spec:
  configuration:
    clusters:
      - name: "standard-02-deployment-pv"
        # Deployment is specified for this cluster explicitly
        deployment:
          podTemplate: pod-template-with-volume
          volumeClaimTemplate: storage-vc-template
        layout:
          type: Standard
          shardsCount: 1
          replicasCount: 1

  templates:
    podTemplates:
      - name: pod-template-with-volume
        containers:
          - name: clickhouse
            image: yandex/clickhouse-server:19.3.7
            ports:
              - name: http
                containerPort: 8123
              - name: client
                containerPort: 9000
              - name: interserver
                containerPort: 9009
            volumeMounts:
              - name: clickhouse-data-storage
                mountPath: /var/lib/clickhouse

    volumeClaimTemplates:
      - name: storage-vc-template
        persistentVolumeClaim:
          metadata:
            name: clickhouse-data-storage
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
