apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "advanced-01"
spec:
  configuration:
    clusters:
      - name: adv
        layout:
          shards:
            - replicas:
                - templates:
                    podTemplate: clickhouse:19.1.10
                - templates:
                    podTemplate: clickhouse:19.3.5
                - templates:
                    podTemplate: clickhouse:19.3.7

  templates:
    podTemplates:
      - name: clickhouse:19.3.7
        spec:
          containers:
            - name: clickhouse-pod
              #        image: yandex/clickhouse-server:19.3.5
              image: yandex/clickhouse-server:19.3.7
              #        image: yandex/clickhouse-server:19.1.10
              #        image: yandex/clickhouse-server:19.1.105
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009

      - name: clickhouse:19.3.5
        spec:
          containers:
            - name: clickhouse-pod
              #        image: yandex/clickhouse-server:19.3.5
              image: yandex/clickhouse-server:19.3.7
              #        image: yandex/clickhouse-server:19.1.10
              #        image: yandex/clickhouse-server:19.1.105
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009

      - name: clickhouse:19.1.10
        spec:
          containers:
            - name: clickhouse-pod
              #        image: yandex/clickhouse-server:19.3.5
              image: yandex/clickhouse-server:19.3.7
              #        image: yandex/clickhouse-server:19.1.10
              #        image: yandex/clickhouse-server:19.1.105
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
