apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "version-update"
spec:
  configuration:
    clusters:
      - name: update
        deployment:
          podTemplate: clickhouse:19.3.7
        layout:
          type: Advanced
          shards:
            - definitionType: Replicas
              replicas:
                - port: 9000
                - port: 9000
                - port: 9000

  templates:
    podTemplates:
      - name: clickhouse:19.3.7
        containers:
          - name: clickhouse-pod
            image: yandex/clickhouse-server:19.3.7
            ports:
              - name: http
                containerPort: 8123
              - name: client
                containerPort: 9000
              - name: interserver
                containerPort: 9009
