apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "update-emptydir"
spec:
  configuration:
    clusters:
      - name: "sharded"
        templates:
          podTemplate: clickhouse-with-empty-dir-volume-template
        layout:
          shardsCount: 4
  templates:
    podTemplates:
      - name: clickhouse-with-empty-dir-volume-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.3.7
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: clickhouse-storage
              emptyDir:
                medium: "" #accepted values:  empty str (means node's default medium) or Memory
                sizeLimit: 1Gi
