#
# AWS-specific labels, applicable in 'nodeAffinity' statements
#
# beta.kubernetes.io/arch=amd64
# beta.kubernetes.io/instance-type=t2.medium
# beta.kubernetes.io/os=linux
#
# failure-domain.beta.kubernetes.io/region=us-east-1
# failure-domain.beta.kubernetes.io/zone=us-east-1a
#
# kubernetes.io/hostname=ip-172-20-37-97.ec2.internal
# kubernetes.io/role=node
# node-role.kubernetes.io/node=
#
# kops.k8s.io/instancegroup=nodes2
#
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "aws-zones"
spec:
  configuration:
    clusters:
      - name: zoned-cluster
        layout:
          shards:
            - replicas:
                - templates:
                    podTemplate: clickhouse-in-zone-us-east-1a
                - templates:
                    podTemplate: clickhouse-in-zone-us-east-1a
                - templates:
                    podTemplate: clickhouse-in-zone-us-east-1a
                - templates:
                    podTemplate: clickhouse-in-zone-us-east-1b
                - templates:
                    podTemplate: clickhouse-in-zone-us-east-1b
                - templates:
                    podTemplate: clickhouse-in-zone-us-east-1b

  templates:
    podTemplates:
      # Specify Pod Templates with affinity

      - name: clickhouse-in-zone-us-east-1a
        spec:
          affinity:
            # Specify Pod affinity to nodes in specified availability zone
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "failure-domain.beta.kubernetes.io/zone"
                        operator: In
                        values:
                          - "us-east-1a"
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.3.7
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009

      - name: clickhouse-in-zone-us-east-1b
        spec:
          affinity:
            # Specify Pod affinity to nodes in specified availability zone
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "failure-domain.beta.kubernetes.io/zone"
                        operator: In
                        values:
                          - "us-east-1b"
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.3.7
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
