apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-installation-test"
spec:
  defaults:
    replicasUseFQDN: 0 # 0 - by default, 1 - enabled
    distributedDDL:
      profile: default
    deployment:
      zone:
        matchLabels:
          clickhouse.altinity.com/zone: zone1
      podTemplateName: clickhouse-installation
      volumeClaimTemplate: default
#     scenario: Default
#
#     default value
# 
  configuration:
    zookeeper:
      nodes:
        - host: zk-statefulset-0.zk-service.default.svc.cluster.local
          port: 2181
        - host: zk-statefulset-1.zk-service.default.svc.cluster.local
          port: 2181
        - host: zk-statefulset-2.zk-service.default.svc.cluster.local
          port: 2181

    users:
      profiles/readonly/readonly: "1"
#      <profiles>
#        <readonly>
#          <readonly>1</readonly>
#        </readonly>
#      </profiles>
    settings:
      profiles/default/max_memory_usage: "1000000000"
#      <profiles>
#        <default>
#          <max_memory_usage>1000000000</max_memory_usage>
#        </default>
#      </profiles>
      compression/case/method: "zstd"
#      <compression>
#       <case>
#         <method>zstd</method>
#      </case>
#      </compression>
    clusters:
    - name: sharded-replicated
      layout:
        type: Standard
        shardsCount: 3
        replicasCount: 2
      deployment:
        podTemplateName: clickhouse-installation
#       scanario: Default
#       zone:
#         matchLabels:
#           clickhouse.altinity.com/zone: zone1
# 
#       values inherited from global .spec.deployment section
#
    - name: sharded-non-replicated
      layout:
        type: Standard
        shardsCount: 3 # replicasCount = 1, by default
      deployment:
        zone:
          matchLabels:
            clickhouse.altinity.com/zone: zone2
#       scenario: Default
#       podTemplateName: clickhouse-installation
#
#       values inherited from global .spec.deployment section
#
    - name: replicated
      layout:
        type: Standard
        replicasCount: 4 # shardsCount = 1, by default
#     deployment:
#       podTemplateName: clickhouse-installation
#       scanario: Default
#       zone:
#         matchLabels:
#           clickhouse.altinity.com/zone: zone1
# 
#       values inherited from global .spec.deployment section
#
    - name: customized
#     deployment:
#       scenario: Default
#       zone:
#         matchLabels:
#           clickhouse.altinity.com/zone: zone1
#       podTemplateName: clickhouse-installation
#
#       values inherited from global .spec.deployment section
#
      layout:
        type: Advanced
        shards:
        - definitionType: ReplicasCount
          replicasCount: 2
          weight: 1
#         weight - omitted by default
          internalReplication: Disabled
#         internalReplication: Enabled - default value
          deployment:
            podTemplateName: clickhouse-installation
            zone:
              matchLabels:
                clickhouse.altinity.com/zone: zone3
#           scenario: Default
#         
#           values inherited from .spec.configuration.clusters[3].deployment section
#
        - definitionType: ReplicasCount
          replicasCount: 3
#         deployment:
#           scenario: Default
#           zone:
#             matchLabels:
#               clickhouse.altinity.com/zone: zone1
#           podTemplateName: clickhouse-installation
#  
#         values inherited from .spec.configuration.clusters[3].deployment section
#  
        - definitionType: Replicas
#         deployment:
#           scenario: Default
#           zone:
#             matchLabels:
#               clickhouse.altinity.com/zone: zone1
#           podTemplateName: clickhouse-installation
#
#         values inherited from .spec.configuration.clusters[3].deployment section
#
          replicas:
          - port: 9000
            deployment:
              scenario: Default
#             zone:
#               matchLabels:
#                 clickhouse.altinity.com/zone: zone1
#             podTemplateName: clickhouse-installation
#  
#           values inherited from .spec.configuration.clusters[3].shards[2].deployment section
#           
          - deployment:
              scenario: NodeMonopoly # 1 pod (CH server instance) per node (zone can be a set of n nodes) -> podAntiAffinity
              zone:
                matchLabels:
                  clickhouse.altinity.com/zone: zone4
                  clickhouse.altinity.com/kind: ssd
              podTemplateName: clickhouse-installation
  templates:
    volumeClaimTemplates:
    - name: default
      template:
        metadata:
          name: clickhouse-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    podTemplates:
    - name: clickhouse-installation
      volumes:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server:18.14.19-stable
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: client
        image: yandex/clickhouse-client:18.14.19-stable
      - name: logwatcher
        image: path/tologwatcher:1.2.3
