{
 "title": "ClickHouseKeeper Dashboard",
 "tags": [
  "altinity",
  "clickhouse-keeper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(zk_ruok, namespace)"
   },
   {
    "name": "pod_name",
    "query": "label_values(zk_ruok, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "avg {{namespace}}.{{pod_name}}"
    },
    {
     "expr": "zk_max_latency{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "max {{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Packets per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zk_packets_sent{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}[1m])",
     "legendFormat": "OUT {{namespace}}.{{pod_name}}"
    },
    {
     "expr": "-irate(zk_packets_received{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}[1m])",
     "legendFormat": "IN {{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "ZNode count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zk_znode_count{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_watch_count{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Ethermals nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_ephemerals_count{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory data size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zk_outstanding_requests{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}[1m])",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{namespace=~\"$namespace\", pod_name=~\"$pod_name\", container_name=\"clickhouse-keeper\"}",
     "legendFormat": "{{namespace}}.{{pod_name}}"
    }
   ]
  }
 ]
}