apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: openebs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-lvm-test