# Possible Template Parameters:
#
# ${OPERATOR_NAMESPACE}
# ${OPERATOR_IMAGE}
# ${CONFIGMAP_NAME}
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CONFIGMAP_NAME}
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: clickhouse-operator
data:
