// Copyright 2019 Altinity Ltd and/or its affiliates. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package namer

import (
	"fmt"
	"strconv"

	api "github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1"
)

// IsAutoGeneratedShardName checks whether provided name is auto-generated
func IsAutoGeneratedShardName(name string, shard api.IShard, index int) bool {
	return name == createShardName(shard, index)
}

// IsAutoGeneratedReplicaName checks whether provided name is auto-generated
func IsAutoGeneratedReplicaName(name string, replica api.IReplica, index int) bool {
	return name == createReplicaName(replica, index)
}

// isBareNumberName checks whether name is a bare non-negative integer in canonical form
// ("3" is, "03" and "-3" are not)
func isBareNumberName(name string) bool {
	i, err := strconv.Atoi(name)
	return (err == nil) && (i >= 0) && (strconv.Itoa(i) == name)
}

// CanonicalizeNumericHostName builds the position-independent canonical name for a host with
// an explicitly specified bare-number name and reports whether canonicalization applies.
//
// A bare-number host name is an identity, not a position. IsAutoGeneratedHostName matches such
// names against patterns derived from the host's CURRENT indexes, so the meaning of "3" would
// change when a preceding entry is removed from the hosts list: the host silently gets another
// name and, with it, another StatefulSet and an empty PVC. To keep the identity stable, the
// number is substituted into the current naming scheme (see createHostName) along the axis the
// hosts list varies on:
//   - hosts declared under a shard vary along the replica axis: "3" -> "{shard}-3"
//   - hosts declared under a replica vary along the shard axis:  "3" -> "3-{replica}"
//
// When hosts are declared both ways, the provenance of a host is unknown and no
// canonicalization is performed.
func CanonicalizeNumericHostName(
	name string,
	shard api.IShard,
	replica api.IReplica,
	hostsUnderShards bool,
	hostsUnderReplicas bool,
) (string, bool) {
	if !isBareNumberName(name) {
		return "", false
	}
	switch {
	case hostsUnderShards && !hostsUnderReplicas:
		return fmt.Sprintf("%s-%s", shard.GetName(), name), true
	case hostsUnderReplicas && !hostsUnderShards:
		return fmt.Sprintf("%s-%s", name, replica.GetName()), true
	default:
		return "", false
	}
}

// IsAutoGeneratedHostName checks whether name is auto-generated
func IsAutoGeneratedHostName(
	name string,
	host *api.Host,
	shard api.IShard,
	shardIndex int,
	replica api.IReplica,
	replicaIndex int,
) bool {
	switch {
	case name == createHostName(host, shard, shardIndex, replica, replicaIndex):
		// Current version of the name
		return true
	case name == fmt.Sprintf("%d-%d", shardIndex, replicaIndex):
		// old version - index-index
		return true
	case name == fmt.Sprintf("%d", shardIndex):
		// old version - index
		return true
	case name == fmt.Sprintf("%d", replicaIndex):
		// old version - index
		return true
	default:
		return false
	}
}
