// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/altinity/clickhouse-operator/pkg/client/clientset/versioned/typed/clickhouse.altinity.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClickhouseV1 struct {
	*testing.Fake
}

func (c *FakeClickhouseV1) ClickHouseInstallations(namespace string) v1.ClickHouseInstallationInterface {
	return &FakeClickHouseInstallations{c, namespace}
}

func (c *FakeClickhouseV1) ClickHouseInstallationTemplates(namespace string) v1.ClickHouseInstallationTemplateInterface {
	return &FakeClickHouseInstallationTemplates{c, namespace}
}

func (c *FakeClickhouseV1) ClickHouseOperatorConfigurations(namespace string) v1.ClickHouseOperatorConfigurationInterface {
	return &FakeClickHouseOperatorConfigurations{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClickhouseV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
