/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1"
	scheme "github.com/altinity/clickhouse-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClickHouseInstallationTemplatesGetter has a method to return a ClickHouseInstallationTemplateInterface.
// A group's client should implement this interface.
type ClickHouseInstallationTemplatesGetter interface {
	ClickHouseInstallationTemplates(namespace string) ClickHouseInstallationTemplateInterface
}

// ClickHouseInstallationTemplateInterface has methods to work with ClickHouseInstallationTemplate resources.
type ClickHouseInstallationTemplateInterface interface {
	Create(ctx context.Context, clickHouseInstallationTemplate *v1.ClickHouseInstallationTemplate, opts metav1.CreateOptions) (*v1.ClickHouseInstallationTemplate, error)
	Update(ctx context.Context, clickHouseInstallationTemplate *v1.ClickHouseInstallationTemplate, opts metav1.UpdateOptions) (*v1.ClickHouseInstallationTemplate, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClickHouseInstallationTemplate, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClickHouseInstallationTemplateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClickHouseInstallationTemplate, err error)
	ClickHouseInstallationTemplateExpansion
}

// clickHouseInstallationTemplates implements ClickHouseInstallationTemplateInterface
type clickHouseInstallationTemplates struct {
	client rest.Interface
	ns     string
}

// newClickHouseInstallationTemplates returns a ClickHouseInstallationTemplates
func newClickHouseInstallationTemplates(c *ClickhouseV1Client, namespace string) *clickHouseInstallationTemplates {
	return &clickHouseInstallationTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clickHouseInstallationTemplate, and returns the corresponding clickHouseInstallationTemplate object, and an error if there is any.
func (c *clickHouseInstallationTemplates) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClickHouseInstallationTemplate, err error) {
	result = &v1.ClickHouseInstallationTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClickHouseInstallationTemplates that match those selectors.
func (c *clickHouseInstallationTemplates) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClickHouseInstallationTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClickHouseInstallationTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clickHouseInstallationTemplates.
func (c *clickHouseInstallationTemplates) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clickHouseInstallationTemplate and creates it.  Returns the server's representation of the clickHouseInstallationTemplate, and an error, if there is any.
func (c *clickHouseInstallationTemplates) Create(ctx context.Context, clickHouseInstallationTemplate *v1.ClickHouseInstallationTemplate, opts metav1.CreateOptions) (result *v1.ClickHouseInstallationTemplate, err error) {
	result = &v1.ClickHouseInstallationTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clickHouseInstallationTemplate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clickHouseInstallationTemplate and updates it. Returns the server's representation of the clickHouseInstallationTemplate, and an error, if there is any.
func (c *clickHouseInstallationTemplates) Update(ctx context.Context, clickHouseInstallationTemplate *v1.ClickHouseInstallationTemplate, opts metav1.UpdateOptions) (result *v1.ClickHouseInstallationTemplate, err error) {
	result = &v1.ClickHouseInstallationTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		Name(clickHouseInstallationTemplate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clickHouseInstallationTemplate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clickHouseInstallationTemplate and deletes it. Returns an error if one occurs.
func (c *clickHouseInstallationTemplates) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clickHouseInstallationTemplates) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clickHouseInstallationTemplate.
func (c *clickHouseInstallationTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClickHouseInstallationTemplate, err error) {
	result = &v1.ClickHouseInstallationTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clickhouseinstallationtemplates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
