apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template-pod"
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.7
              ports:
                - name: http
                  containerPort: 8124
                - name: tcp
                  containerPort: 9001
                - name: interserver
                  containerPort: 9010
