apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template-pod"
  finalizers:
    - finalizer.clickhouseinstallation.altinity.com
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
    clusters:
      - name: "temp-pod"
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.8
              # Container has explicitly specified resource requests
              resources:
                requests:
                  cpu: "1000m"
              # Container has explicitly specified ports
              ports:
                - name: http
                  containerPort: 8124
                - name: tcp
                  containerPort: 9001
                - name: interserver
                  containerPort: 9010
