apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template-override"
spec:
  configuration:
    clusters:
      - name: "c1"
  templates:
    volumeClaimTemplates:
      - name: default-volumeclaim-template
        spec:
          resources:
            requests:
              storage: 4Gi
