#
# AWS resizable disk example
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
#volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "pv-resize"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
  configuration:
    clusters:
      - name: "pv-resize"
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
