#
# AWS encrypted disk example
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-encrypted
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  # FS ext4 start encrypted disk quickly
  # FS xfs start encrypted disk very slow - easy can be said "does not work at all for me"
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Delete
#volumeBindingMode: Immediate
#allowVolumeExpansion: true
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "pv-enc"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
  configuration:
    clusters:
      - name: "pv-enc"
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          storageClassName: gp2-encrypted
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi

