apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "repl-02"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo3ns
          port: 2181
        - host: zookeeper-1.zookeepers.zoo3ns
          port: 2181
        - host: zookeeper-2.zookeepers.zoo3ns
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: /path/to/zookeeper/node
      identity: user:password
    clusters:
      - name: replcluster
        layout:
          shardsCount: 3
          replicasCount: 2
