apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "adv-layout-repl"
spec:
  configuration:
    clusters:
      - name: adv
        layout:
          shardsCount: 4
          replicas:
            - templates:
                podTemplate: clickhouse:20.5
              httpPort: 8000
              tcpPort: 8001
              interserverHTTPPort: 8002
            - templates:
                podTemplate: clickhouse:20.6
              httpPort: 9000
              tcpPort: 9001
              interserverHTTPPort: 9002
            - templates:
                podTemplate: clickhouse:20.7
              httpPort: 10000
              tcpPort: 10001
              interserverHTTPPort: 10002

  templates:
    podTemplates:

      - name: clickhouse:20.5
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.5

      - name: clickhouse:20.6
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.6


      - name: clickhouse:20.7
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
