apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "adv-layout-shard"
spec:
  configuration:
    clusters:
      - name: adv
        layout:
          shards:
            - replicas:
                - templates:
                    podTemplate: clickhouse:23.8
                  httpPort: 8000
                  tcpPort: 8001
                  interserverHTTPPort: 8002
                - templates:
                    podTemplate: clickhouse:24.3
                  httpPort: 9000
                  tcpPort: 9001
                  interserverHTTPPort: 9002
                - templates:
                    podTemplate: clickhouse:24.8
                  httpPort: 10000
                  tcpPort: 10001
                  interserverHTTPPort: 10002

  templates:
    podTemplates:

      - name: clickhouse:23.8
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8

      - name: clickhouse:24.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.3


      - name: clickhouse:24.8
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.8
