apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "version-update"
spec:
  configuration:
    clusters:
      - name: update
        templates:
          podTemplate: clickhouse:23.8
        layout:
          shards:
            - replicas:
                - tcpPort: 9000
                - tcpPort: 9000
                - tcpPort: 9000

  templates:
    podTemplates:
      - name: clickhouse:23.8
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8
