apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "version-update"
spec:
  configuration:
    clusters:
      - name: update
        templates:
          podTemplate: clickhouse:20.6
        layout:
          shards:
            - replicas:
                - tcpPort: 9000
                - tcpPort: 9000
                - tcpPort: 9000
                  templates:
                    podTemplate: clickhouse:20.7

  templates:
    podTemplates:
      - name: clickhouse:20.6
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.6

      - name: clickhouse:20.7
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
