apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "update-emptydir"
spec:
  configuration:
    clusters:
      - name: "sharded"
        templates:
          podTemplate: clickhouse-with-empty-dir-volume-template
        layout:
          shardsCount: 4
  templates:
    podTemplates:
      - name: clickhouse-with-empty-dir-volume-template
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.8
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: clickhouse-storage
              emptyDir:
                medium: "" # accepted values:  empty str (means node's default medium) or "Memory"
                sizeLimit: 1Gi
