#
# AWS-specific labels, applicable in 'nodeAffinity' statements
#
# beta.kubernetes.io/arch=amd64
# beta.kubernetes.io/instance-type=t2.medium
# beta.kubernetes.io/os=linux
#
# failure-domain.beta.kubernetes.io/region=us-east-1
# failure-domain.beta.kubernetes.io/zone=us-east-1a
#
# kubernetes.io/hostname=ip-172-20-37-97.ec2.internal
# kubernetes.io/role=node
# node-role.kubernetes.io/node=
#
# kops.k8s.io/instancegroup=nodes2
#
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch-per-host-localstorage"
spec:
  defaults:
    templates:
      podTemplate: clickhouse-per-host-localstorage
      serviceTemplate: ch-service
  configuration:
    clusters:
      - name: ch-localstorage
        layout:
          shardsCount: 2
  templates:
    serviceTemplates:
      - name: ch-service
        generateName: chendpoint
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
    podTemplates:
      # Specify Pod Templates with affinity
      - name: clickhouse-per-host-localstorage
        zone:
          key: "clickhouse"
          values:
            - "allow"
        podDistribution:
          - type: ClickHouseAntiAffinity
        spec:
          volumes:
            # Specify volume as path on local filesystem as a directory which will be created, if need be
            - name: local-path
              hostPath:
                path: /mnt/data/clickhouse-test
                type: DirectoryOrCreate
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8
              volumeMounts:
                - name: local-path
                  mountPath: /var/lib/clickhouse
