#
# AWS-specific labels, applicable in 'nodeAffinity' statements
#
# beta.kubernetes.io/arch=amd64
# beta.kubernetes.io/instance-type=t2.medium
# beta.kubernetes.io/os=linux
#
# failure-domain.beta.kubernetes.io/region=us-east-1
# failure-domain.beta.kubernetes.io/zone=us-east-1a
#
# kubernetes.io/hostname=ip-172-20-37-97.ec2.internal
# kubernetes.io/role=node
# node-role.kubernetes.io/node=
#
# kops.k8s.io/instancegroup=nodes2
#
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "zones-pod-host"
spec:
  defaults:
    templates:
      podTemplate: clickhouse-per-host-in-zone-us-east-1a
  configuration:
    clusters:
      - name: zoned-cluster
        layout:
          shardsCount: 3

  templates:
    podTemplates:
      # Specify Pod Templates with affinity
      - name: clickhouse-per-host-in-zone-us-east-1a
        zone:
          values:
            - "us-east-1a"
        podDistribution:
          - type: "ClickHouseAntiAffinity"
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8
