apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "troubleshoot-01"
spec:
  configuration:
    clusters:
      - name: "t1"
        templates:
          podTemplate: pod-template
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              command:
                - "/bin/bash"
                - "-c"
                - "/entrypoint.sh; while true; do sleep 3600; done"
