apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "hostnet1"
spec:
  defaults:
    templates:
      podTemplate: pod-distribution

  configuration:
    clusters:
      - name: "hnet1"
        layout:
          shardsCount: 2
          replicasCount: 3

  templates:
    podTemplates:
      - name: pod-distribution
        podDistribution:
          - type: CircularReplication
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
