apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: skip-user
spec:
  configuration:
    clusters:
      - name: cluster
        layout:
          replicasCount: 1
          shardsCount: 1
  templates:
    podTemplates:
      - name: skip-user
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              env:
                - name: CLICKHOUSE_SKIP_USER_SETUP
                  value: "1"
  defaults:
    templates:
      podTemplate: skip-user

