apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: "simple-template-01"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
      logVolumeClaimTemplate: log-volumeclaim-template
  templates:
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      - name: log-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  templating:
    policy: auto
