apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: chit-04
  annotations:
    chit-04-annotation: chit-04-annotation-value
spec:
  defaults:
    templates:
      logVolumeClaimTemplate: log-volumeclaim-template
  templates:
    volumeClaimTemplates:
      - name: log-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  templating:
    policy: auto
    # chiSelector works exactly as nodeSelector
    # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
    # Specify labels of the target CHIs to apply this CHIT
    chiSelector:
      target-chi-label-auto: target-chi-label-auto-value
