apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: evolution
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoo1ns
    clusters:
      - name: cluster
        # Templates are specified for this cluster explicitly
        templates:
          podTemplate: pod-template-with-volume
        layout:
          shardsCount: 2
          replicasCount: 2
          shards:
            - name: "1"
              replicasCount: 2
              replicas:
                - name: "1"
                  templates:
                    podTemplate: pod-template-with-volume-23.3

  templates:
    podTemplates:
      - name: pod-template-with-volume
        zone:
          key: "clickhouse"
          values:
            - "allow"
        podDistribution:
          - type: ClickHouseAntiAffinity
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.3
              volumeMounts:
                - name: storage-vc-template
                  mountPath: /var/lib/clickhouse

      - name: pod-template-with-volume-23.3
        zone:
          key: "clickhouse"
          values:
            - "allow"
        podDistribution:
          - type: ClickHouseAntiAffinity
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              volumeMounts:
                - name: storage-vc-template
                  mountPath: /var/lib/clickhouse

    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
