# References:
# - https://github.com/Altinity/clickhouse-operator/blob/0.9.0/deploy/operator/clickhouse-operator-install.yaml#L1294
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defaultObjectFullName" . }}-operator-config
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
data:
  config.yaml: |
{{- if .Values.operator.watchNamespaces }}
    watchNamespaces: {{ toJson .Values.operator.watchNamespaces }}
{{- end }}
    chCommonConfigsPath: config.d
    chHostConfigsPath: conf.d
    chUsersConfigsPath: users.d
    chiTemplatesPath: templates.d
    statefulSetUpdateTimeout: {{ .Values.operator.statefulSetUpdateTimeout }}
    statefulSetUpdatePollPeriod: {{ .Values.operator.statefulSetUpdatePollPeriod }}
    onStatefulSetCreateFailureAction: {{ .Values.operator.onStatefulSetCreateFailureAction }}
    onStatefulSetUpdateFailureAction: {{ .Values.operator.onStatefulSetUpdateFailureAction }}
    chConfigUserDefaultProfile: default
    chConfigUserDefaultQuota: default
    chConfigUserDefaultNetworksIP:
      - "::1"
      - "127.0.0.1"
    chConfigUserDefaultPassword: "default"
    ChConfigNetworksHostRegexpTemplate: "chi-{chi}-[^.]+\\d+-\\d+\\.{namespace}.svc.cluster.local$"
    chUsername: clickhouse_operator
    chPassword: clickhouse_operator_password
    chPort: 8123
