// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClickHouseInstallations returns a ClickHouseInstallationInformer.
	ClickHouseInstallations() ClickHouseInstallationInformer
	// ClickHouseInstallationTemplates returns a ClickHouseInstallationTemplateInformer.
	ClickHouseInstallationTemplates() ClickHouseInstallationTemplateInformer
	// ClickHouseOperatorConfigurations returns a ClickHouseOperatorConfigurationInformer.
	ClickHouseOperatorConfigurations() ClickHouseOperatorConfigurationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClickHouseInstallations returns a ClickHouseInstallationInformer.
func (v *version) ClickHouseInstallations() ClickHouseInstallationInformer {
	return &clickHouseInstallationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClickHouseInstallationTemplates returns a ClickHouseInstallationTemplateInformer.
func (v *version) ClickHouseInstallationTemplates() ClickHouseInstallationTemplateInformer {
	return &clickHouseInstallationTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClickHouseOperatorConfigurations returns a ClickHouseOperatorConfigurationInformer.
func (v *version) ClickHouseOperatorConfigurations() ClickHouseOperatorConfigurationInformer {
	return &clickHouseOperatorConfigurationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
