apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: incorrect-pod-template
spec:
  templates:
    podTemplates:
    - name: clickhouse-pod-template
      containers:
      - name: clickhouse-pod
        image: yandex/clickhouse-server:19.3.4
        ports:
        - name: http
          containerPort: 8123
        - name: client
          containerPort: 9000
        - name: interserver
          containerPort: 9009
        # Specify extremely limited memory resources
        # ClickHouse would be killed by OOM and Pod passes through 'OOMKilled' state into 'CrashLoopBackOff'
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 32Mi
  configuration:
    clusters:
    - name: incorrect-pod-template
      layout:
        type: Standard
        shardsCount: 3
        replicasCount: 1
      deployment:
        podTemplate: clickhouse-pod-template

