{
 "title": "Kafka Dashboard",
 "description": "Alitinity Clickhouse Operator metrics exported by Monitoring Agent",
 "tags": [
  "Altinity",
  "clickhouse",
  "operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" },
   {
    "name": "exported_namespace",
    "label": "K8S Namespace",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\"}, exported_namespace)"
    }
   },
   {
    "name": "chi",
    "label": "K8S Clickhouse Installation",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\", exported_namespace=~\"$exported_namespace\"}, chi)"
    }
   },
   {
    "name": "hostname",
    "label": "Server",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\",exported_namespace=~\"$exported_namespace\",chi=~\"$chi\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka active consumers",
   "type": "graph",
   "description": "Number of Kafka active consumers",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaConsumers{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka consumers with assignments",
   "type": "graph",
   "description": "Number of active Kafka consumers which have some partitions assigned. ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaConsumersWithAssignment{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka consumers in use",
   "type": "graph",
   "description": "Number of consumers which are currently used by direct or background reads (MVs)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaConsumersInUse{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka Assigned Partitions",
   "type": "graph",
   "description": "Number of partitions Kafka tables currently assigned to",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaAssignedPartitions{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka consumer Errors",
   "type": "graph",
   "description": "KafkaConsumerErrors, \"Number of errors reported by librdkafka during polls\"\n\nKafkaProducerFlushes, \"Number of explicit flushes to Kafka producer\"\n",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaConsumerErrors{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka rebalance assignments",
   "type": "graph",
   "description": "Number of partition assignments (the first stage of consumer group rebalance)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaRebalanceAssignments{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka rebalance revocations",
   "type": "graph",
   "description": "Number of partition revocations (the first stage of consumer group rebalance)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaRebalanceRevocations{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka rebalance  errors",
   "type": "graph",
   "description": "Number of partition relabance errors (the first stage of consumer group rebalance)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaRebalanceRevocations{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "rate(chi_clickhouse_event_KafkaRebalanceAssignments{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "rate(chi_clickhouse_event_KafkaRebalanceErrors{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka commits",
   "type": "graph",
   "description": "KafkaCommits, \"Number of successful commits of consumed offsets to Kafka (normally should be the same as KafkaBackgroundReads)\"",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaCommits{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka commit failures",
   "type": "graph",
   "description": "KafkaCommitFailures, \"Number of failed commits of consumed offsets to Kafka (usually is a sign of some data duplication)\"(due to rebalances / errors or similar reasons). Those rows will be consumed again after the rebalance.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaCommitFailures{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka Background Reads",
   "type": "graph",
   "description": "Number of background reads currently working (populating materialized views from Kafka)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaBackgroundReads{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka messages read",
   "type": "graph",
   "description": "Number of kafka read messages from librdkafka to ClickHouse",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaMessagesRead{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka messages polled",
   "type": "graph",
   "description": "Number of Kafka messages polled  from librdkafka to ClickHouse",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaMessagesPolled{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka messages failed",
   "type": "graph",
   "description": "Number of Kafka messages failed from librdkafka to ClickHouse",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaMessagesFailed{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka LibrdKafka Threads",
   "type": "graph",
   "description": "│ KafkaLibrdkafkaThreads       │     0 │ Number of active librdkafka threads                                                     │\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaLibrdkafkaThreads{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka rows read",
   "type": "graph",
   "description": "Number of rows parsed from Kafka messages",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaRowsRead{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka rows rejected",
   "type": "graph",
   "description": "Number of parsed rows which were later rejected (due to rebalances / errors or similar reasons). Those rows will be consumed again after the rebalance.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaRowsRejected{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka background reads",
   "type": "graph",
   "description": "KafkaBackgroundReads, \"Number of background reads populating materialized views from Kafka since server start\"",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaBackgroundReads{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka Writes by producers (Current INSERTs)",
   "type": "graph",
   "description": "Number of currently running inserts to Kafka  ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaWrites{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka writes (INSERTs) by producers",
   "type": "graph",
   "description": "KafkaWrites, \"Number of writes (inserts) to Kafka tables \"\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaWrites{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka producer errors",
   "type": "graph",
   "description": "KafkaProducerErrors, \"Number of errors during producing the messages to Kafka\"\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaProducerErrors{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka active producers",
   "type": "graph",
   "description": "Kafka Producers active",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_KafkaProducers{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka messages produced",
   "type": "graph",
   "description": "KafkaMessagesProduced, \"Number of messages produced to Kafka\"\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaMessagesProduced{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka rows written by producers",
   "type": "graph",
   "description": "KafkaRowsWritten, \"Number of rows inserted into Kafka tables\"\n\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_KafkaRowsWritten{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}