// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClickHouseInstallationListerExpansion allows custom methods to be added to
// ClickHouseInstallationLister.
type ClickHouseInstallationListerExpansion interface{}

// ClickHouseInstallationNamespaceListerExpansion allows custom methods to be added to
// ClickHouseInstallationNamespaceLister.
type ClickHouseInstallationNamespaceListerExpansion interface{}

// ClickHouseInstallationTemplateListerExpansion allows custom methods to be added to
// ClickHouseInstallationTemplateLister.
type ClickHouseInstallationTemplateListerExpansion interface{}

// ClickHouseInstallationTemplateNamespaceListerExpansion allows custom methods to be added to
// ClickHouseInstallationTemplateNamespaceLister.
type ClickHouseInstallationTemplateNamespaceListerExpansion interface{}

// ClickHouseOperatorConfigurationListerExpansion allows custom methods to be added to
// ClickHouseOperatorConfigurationLister.
type ClickHouseOperatorConfigurationListerExpansion interface{}

// ClickHouseOperatorConfigurationNamespaceListerExpansion allows custom methods to be added to
// ClickHouseOperatorConfigurationNamespaceLister.
type ClickHouseOperatorConfigurationNamespaceListerExpansion interface{}
