// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: pkg/plugin/proto/backup.proto

package backup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to initiate a backup
type BackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. JSON serialization of the CHI being backed up
	ChiDefinition []byte `protobuf:"bytes,1,opt,name=chi_definition,json=chiDefinition,proto3" json:"chi_definition,omitempty"`
	// REQUIRED. JSON serialization of the Backup object
	BackupDefinition []byte `protobuf:"bytes,2,opt,name=backup_definition,json=backupDefinition,proto3" json:"backup_definition,omitempty"`
	// } Backup configuration parameters (from Backup or ScheduledBackup object)
	Parameters    map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_pkg_plugin_proto_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetChiDefinition() []byte {
	if x != nil {
		return x.ChiDefinition
	}
	return nil
}

func (x *BackupRequest) GetBackupDefinition() []byte {
	if x != nil {
		return x.BackupDefinition
	}
	return nil
}

func (x *BackupRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Result returned after backup completes
type BackupResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Machine-readable ID of the backup
	BackupId string `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// OPTIONAL. Human-readable name of the backup
	BackupName string `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// REQUIRED. Unix timestamp of the start time of the backup
	StartedAt int64 `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// REQUIRED. Unix timestamp of the stop time of the backup
	StoppedAt int64 `protobuf:"varint,4,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	// OPTIONAL. Plugin-specific metadata key/values
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResult) Reset() {
	*x = BackupResult{}
	mi := &file_pkg_plugin_proto_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResult) ProtoMessage() {}

func (x *BackupResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResult.ProtoReflect.Descriptor instead.
func (*BackupResult) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupResult) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupResult) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *BackupResult) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *BackupResult) GetStoppedAt() int64 {
	if x != nil {
		return x.StoppedAt
	}
	return 0
}

func (x *BackupResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_plugin_proto_backup_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_backup_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/backup.proto\x12\x12altinity.backup.v1\"\xf5\x01\n" +
	"\rBackupRequest\x12%\n" +
	"\x0echi_definition\x18\x01 \x01(\fR\rchiDefinition\x12+\n" +
	"\x11backup_definition\x18\x02 \x01(\fR\x10backupDefinition\x12Q\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v21.altinity.backup.v1.BackupRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\fBackupResult\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12\x1f\n" +
	"\vbackup_name\x18\x02 \x01(\tR\n" +
	"backupName\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\x04 \x01(\x03R\tstoppedAt\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..altinity.backup.v1.BackupResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012W\n" +
	"\x06Backup\x12M\n" +
	"\x06Backup\x12!.altinity.backup.v1.BackupRequest\x1a .altinity.backup.v1.BackupResultB;Z9github.com/altinity/clickhouse-operator/pkg/plugin/backupb\x06proto3"

var (
	file_pkg_plugin_proto_backup_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_backup_proto_rawDescData []byte
)

func file_pkg_plugin_proto_backup_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_backup_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_backup_proto_rawDesc), len(file_pkg_plugin_proto_backup_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_backup_proto_rawDescData
}

var file_pkg_plugin_proto_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_plugin_proto_backup_proto_goTypes = []any{
	(*BackupRequest)(nil), // 0: altinity.backup.v1.BackupRequest
	(*BackupResult)(nil),  // 1: altinity.backup.v1.BackupResult
	nil,                   // 2: altinity.backup.v1.BackupRequest.ParametersEntry
	nil,                   // 3: altinity.backup.v1.BackupResult.MetadataEntry
}
var file_pkg_plugin_proto_backup_proto_depIdxs = []int32{
	2, // 0: altinity.backup.v1.BackupRequest.parameters:type_name -> altinity.backup.v1.BackupRequest.ParametersEntry
	3, // 1: altinity.backup.v1.BackupResult.metadata:type_name -> altinity.backup.v1.BackupResult.MetadataEntry
	0, // 2: altinity.backup.v1.Backup.Backup:input_type -> altinity.backup.v1.BackupRequest
	1, // 3: altinity.backup.v1.Backup.Backup:output_type -> altinity.backup.v1.BackupResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_backup_proto_init() }
func file_pkg_plugin_proto_backup_proto_init() {
	if File_pkg_plugin_proto_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_backup_proto_rawDesc), len(file_pkg_plugin_proto_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_backup_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_backup_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_backup_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_backup_proto = out.File
	file_pkg_plugin_proto_backup_proto_goTypes = nil
	file_pkg_plugin_proto_backup_proto_depIdxs = nil
}
