apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: "102-default-log-volumeclaimtemplate"
spec:
  templates:
    volumeClaimTemplates:
      - name: default-log-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
