apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: "103-default-pod-template"
spec:
  templates:
    podTemplates:
      - name: default-pod-template
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
