# Setup Service to provide access to clickhouse
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  labels:
    app: clickhouse
spec:
  ports:
  - port: 8123
    name: http
  - port: 9000
    name: client
  - port: 9009
    name: interserver
  selector:
    dns: chi1
