apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-server-config-d-common
data:
  docker_related_config.xml: |-
    <yandex>
         <!-- Listen wildcard address to allow accepting connections from other containers and host network. -->
        <listen_host>::</listen_host>
        <listen_host>0.0.0.0</listen_host>
        <listen_try>1</listen_try>

        <!--
        <logger>
            <console>1</console>
        </logger>
        -->
    </yandex>

  zookeeper.xml: |-
    <yandex>
        <zookeeper>
            <node>
                <host>zookeeper-service-client</host>
                <port>2181</port>
            </node>
        </zookeeper>
    </yandex>

  remote_servers.xml: |-
    <yandex>
        <remote_servers>

            <benchmark_cluster>
                <shard>
                    <replica>
                        <!-- chpod1 -->
                        <host>ch-stateful-set-1-0.ch-node-hs-1</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </benchmark_cluster>

            <repl_cluster>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <!-- chpod1 -->
                        <host>ch-stateful-set-1-0.ch-node-hs-1</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <!-- chpod1 -->
                        <host>ch-stateful-set-1-0.ch-node-hs-1</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </repl_cluster>

        </remote_servers>
    </yandex>

