// Copyright 2019 Altinity Ltd and/or its affiliates. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package config

import (
	"bytes"
	"strings"
	"testing"

	core "k8s.io/api/core/v1"

	chi "github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1"
	"github.com/altinity/clickhouse-operator/pkg/apis/common/types"
)

// TestGetRemoteServersClusterSecret walks the secret-source matrix that drives
// the <secret> element in autogenerated remote_servers.xml clusters.
//
// The helper is a method on *Generator but doesn't dereference the receiver,
// so we invoke it on a nil receiver — keeps the test free of Generator's
// CR / namer / options construction overhead.
func TestGetRemoteServersClusterSecret(t *testing.T) {
	cases := []struct {
		name   string
		secret *chi.ClusterSecret
		want   string
	}{
		{
			name:   "nil secret renders nothing",
			secret: nil,
			want:   "",
		},
		{
			name:   "empty struct (Unspecified source) renders nothing",
			secret: &chi.ClusterSecret{},
			want:   "",
		},
		{
			name:   "plaintext renders inline value",
			secret: &chi.ClusterSecret{Value: "topsecret"},
			want:   "<secret>topsecret</secret>\n",
		},
		{
			name:   "plaintext XML-escapes ampersand",
			secret: &chi.ClusterSecret{Value: "a&b"},
			want:   "<secret>a&amp;b</secret>\n",
		},
		{
			name:   "plaintext XML-escapes angle brackets",
			secret: &chi.ClusterSecret{Value: "<tag>"},
			want:   "<secret>&lt;tag&gt;</secret>\n",
		},
		{
			name:   "plaintext XML-escapes CDATA terminator",
			secret: &chi.ClusterSecret{Value: "x]]>y"},
			// encoding/xml.EscapeText escapes ']]>' to ']]&gt;' to prevent
			// breaking out of a CDATA section that a future renderer might
			// wrap the value in.
			want: "<secret>x]]&gt;y</secret>\n",
		},
		{
			name:   "valueFrom (secret_ref) renders env-var reference",
			secret: &chi.ClusterSecret{ValueFrom: &types.DataSource{SecretKeyRef: &core.SecretKeySelector{}}},
			want:   `<secret from_env="CLICKHOUSE_INTERNODE_CLUSTER_SECRET" />` + "\n",
		},
		{
			name:   "auto renders env-var reference",
			secret: &chi.ClusterSecret{Auto: types.NewStringBool(true)},
			want:   `<secret from_env="CLICKHOUSE_INTERNODE_CLUSTER_SECRET" />` + "\n",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			var b bytes.Buffer
			// Nil receiver — helper doesn't touch *Generator.
			var g *Generator
			g.getRemoteServersClusterSecret(c.secret, 0, &b)
			got := b.String()
			if got != c.want {
				t.Fatalf("output mismatch:\nwant: %q\ngot:  %q", c.want, got)
			}
		})
	}
}

// TestGetRemoteServersClusterSecret_IndentLevel sanity-checks that the indent
// parameter is honoured — caller passes indent+4 at every site, and a
// regression that hardcoded indent would silently misalign the rendered XML.
func TestGetRemoteServersClusterSecret_IndentLevel(t *testing.T) {
	secret := &chi.ClusterSecret{Value: "v"}
	for _, indent := range []int{0, 4, 8, 16} {
		var b bytes.Buffer
		var g *Generator
		g.getRemoteServersClusterSecret(secret, indent, &b)
		out := b.String()
		// util.Iline pads with `indent` spaces before the content.
		wantPrefix := strings.Repeat(" ", indent) + "<secret>"
		if !strings.HasPrefix(out, wantPrefix) {
			t.Fatalf("indent=%d: expected prefix %q, got %q", indent, wantPrefix, out)
		}
	}
}
